[required]
latitude = 31.089   
longitude = -93.128   
elevation = 94.1
start_range = "2025-01-01 00:00"
end_range = "2025-06-01 23:00"

[optional]
outfile = "FtJohnson_nldas2_Jan_Jun_2025_dirint.met"
# metfile = "~/data_repo/TISTEF/Met/NATO_Met_Data.xlsx"
# https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timeseries-offset-aliases
# 5 minutes
# metstation_freq = "1T"
location_name = "Ft Johnson NLDAS2 Data"
# tmp_nldas2_folder = "/path/to/grib_files"
# cleanup_folder = false
# freq = "2H"
pull_nldas2 = true

# Source models for parameters - these default to met (except for zenith and azimuth which default to pvlib)
# Key is where it is found in the met file - these default to the standard names we use but are overridden here
[parameters]
[parameters.pressure]
source = "nldas2"
[parameters.temperature]
source = "nldas2"
[parameters.relative_humidity]
source = "nldas2"
[parameters.wind_speed]
source = "nldas2"
[parameters.wind_direction]
source = "nldas2"
[parameters.precipitation]
source = "nldas2"
[parameters.global_shortwave]
source = "nldas2"
[parameters.direct_shortwave]
source = "pvlib_dirint"
#key = "Direct"
[parameters.diffuse_shortwave]
source = "pvlib_dirint"
#key = "Diffuse"
[parameters.downwelling_lwir]
source = "nldas2"
[parameters.zenith]
source = "pvlib"
[parameters.azimuth]
source = "pvlib"
