from typing import Any
from pydantic import BaseModel, Field, ConfigDict


class InstrumentMetadata(BaseModel):
    """ Optional metadata for instrument provenance tracking """

    instrument: str | None = Field(None,
                                   description="Instrument ID from library (e.g., 'apogee_sp110' or 'pyranometers.apogee_sp110'")

    serial_number: str | None = Field(None, description="Instrument serial number")
    installation_date: str | None = Field(None, description="Instrument installation date")
    installation_height: float | None = Field(None, description="Instrument installation height in meters")

    comment: str | None = Field(None, description="Additional context - appends to autogenerated methodology")
    comment_replace: str | None = Field(None, description="Full override of auto-generated methodology")
    references: str | None = Field(None, description="Additional references (e.g. DOIs, spec sheets, SOPs)")

    accuracy: str | None = Field(None, description="Accuracy specification (overrides library)")
    calibration_date: str | None = Field(None, description="Last calibration date")
    calibration_method: str | None = Field(None, description="Calibration method")

    measurement_height: float | None = Field(None, description="Measurement height (m) - alias for installation_height")
    model_config = ConfigDict(extra="allow")

class DirectionalConfig(BaseModel):
    """
    Config for directional measurements (future radiance cubes)

    Supports up, down, north, south, east, west
    """
    source: str = Field(..., description="Data source for this direction")
    key: str | None = Field(None, description="Key/column name in source data")
    metadata: InstrumentMetadata | None = Field(None, description="Direction-specific metadata")

    model_config = ConfigDict(extra="allow")

class ParameterConfig(BaseModel):
    """
    Config for a single meteorological parameter

        Examples:
        # Minimal (existing style):
        ParameterConfig(source="met", key="AirT_2M")

        # With metadata:
        ParameterConfig(
            source="pvlib_dirindex",
            metadata=InstrumentMetadata(
                comment="Validated against ARM pyrheliometer, RMSE=45 W/m²"
            )
        )
    """
    source: str = Field(..., description="Data source: 'met', 'nldas2', 'pvlib_*', etc")

    key: str | None = Field(None, description="Column/key name in source data")
    fraction: float | None = Field(None, description="Fraction of global_fraction source")

    metadata: InstrumentMetadata | None = Field(None, description="Instrument and methodology metadata")

    directions: dict[str, DirectionalConfig] = Field(None, description="Direction configuration for radiance cubes")

    model_config = ConfigDict(extra="allow", validate_assignment=True)



Parameter = dict[str, Any]
Parameters = dict[str, Parameter]
TypedParameters: dict[str, ParameterConfig]
