from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping

import numpy as np
import pandas as pd
from pandas.tseries.frequencies import to_offset
import xarray as xr

from metforce.data_types import Parameters
from metforce.defaults import default_met_units, default_met_width, default_met_decimal, default_col_names
from metforce.logger_config import logger
from metforce.instruments import InstrumentLibrary, merge_instrument_metadata

# --- Param -> CF var name map ------------------------------------------------
_PARAM_TO_CF = {
    "pressure": "air_pressure",
    "temperature": "air_temperature",
    "relative_humidity": "relative_humidity",
    "wind_speed": "wind_speed",
    "wind_direction": "wind_from_direction",
    "precipitation": "precipitation_amount",
    "global_shortwave": "surface_downwelling_shortwave_flux_in_air",
    "direct_shortwave": "surface_direct_along_beam_shortwave_flux_in_air",
    "diffuse_shortwave": "surface_diffuse_downwelling_shortwave_flux_in_air",
    "downwelling_lwir": "surface_downwelling_longwave_flux_in_air",
}

# --- Core coverage set --------------------------------------------------------
_CORE_VARS = [
    "air_pressure",
    "air_temperature",
    "relative_humidity",
    "wind_speed",
    "wind_from_direction",
    "precipitation_amount",
    "surface_downwelling_shortwave_flux_in_air",
    "surface_downwelling_longwave_flux_in_air",
]
_COVERAGE_THRESHOLD = 0.80


def _normalize_time_index(idx: pd.DatetimeIndex) -> pd.DatetimeIndex:
    """UTC-normalize, monotonic, tz-naive index for CF writing."""
    if idx.tz is not None:
        idx = idx.tz_convert("UTC").tz_localize(None)
    if not idx.is_monotonic_increasing:
        idx = idx.sort_values()
    return pd.DatetimeIndex(idx, tz=None)


def _infer_step(time: pd.DatetimeIndex) -> pd.Timedelta | pd.DateOffset:
    """Robust step inference (works with 2+ timestamps)."""
    if getattr(time, "freq", None) is not None:
        return to_offset(time.freq)
    if len(time) >= 2:
        diffs = pd.Series(time).diff().dropna()
        return diffs.median()
    raise ValueError("Cannot infer time bounds from a single timestamp.")


# =============================================================================
# PROVENANCE GENERATION FUNCTIONS
# =============================================================================

def _detect_sources_from_parameters(parameters: dict[str, Any]) -> list[str]:
    """
    Detect unique data sources from parameters configuration.

    Returns list of source identifiers for global 'source' attribute.
    """
    sources = set()

    for param_config in parameters.values():
        source = param_config.get("source", "").lower()

        # Normalize source names
        if source == "met" or source == "station":
            sources.add("weather_station")
        elif source == "nldas2":
            sources.add("nldas2")
        elif source.startswith("pvlib"):
            sources.add("pvlib_model")
        elif source in ("global_fraction", "global_coszenith"):
            sources.add("derived")
        elif source == "brunt":
            sources.add("derived")
        elif source:
            sources.add(source)

    return sorted(sources)


def _add_streamlined_global_attrs(
        ds: xr.Dataset,
        meta: dict[str, Any],
        parameters: dict[str, Any]
) -> None:
    """
    Add streamlined global attributes

    - Conventions, featureType (CF compliance) - already set
    - title, institution (user-specified)
    - processing_level (hard-coded to 2)
    - history (auto-generated timestamp)
    - source (auto-detected from parameters)
    - geospatial info (from meta)
    - comment (optional, from output config)
    """
    # User-specified core metadata
    if meta.get("title"):
        ds.attrs["title"] = meta["title"]

    if meta.get("institution"):
        ds.attrs["institution"] = meta["institution"]

    if meta.get("comment"):
        ds.attrs["comment"] = meta["comment"]

    # Processing level (hard-coded to 2 per spec - NASA specifications that shouldn't matter to us right now
    ds.attrs["processing_level"] = "2"

    # History (auto-generated)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    ds.attrs["history"] = f"{timestamp}: Generated by metforce"

    # Source (auto-detected)
    sources = _detect_sources_from_parameters(parameters)
    if sources:
        ds.attrs["source"] = " ".join(sources)

    # Geospatial (from meta)
    if meta.get("latitude") is not None:
        ds.attrs["geospatial_latitude"] = float(meta["latitude"])
    if meta.get("longitude") is not None:
        ds.attrs["geospatial_longitude"] = float(meta["longitude"])
    if meta.get("elevation_m") is not None:
        elev = float(meta["elevation_m"])
        ds.attrs["geospatial_vertical_min"] = elev
        ds.attrs["geospatial_vertical_max"] = elev
        ds.attrs["geospatial_vertical_units"] = "m"
        ds.attrs["geospatial_vertical_positive"] = "up"


def _add_station_provenance(
        ds: xr.Dataset,
        cf_var: str,
        param_config: dict[str, Any],
        merged_metadata: dict[str, Any]
) -> None:
    """
    Add provenance for station-measured variables.

    Documents:
    - Measurement type (in situ)
    - Instrument specifications (from library if available)
    - Deployment details (from config)
    - Quality assessment
    """
    ds[cf_var].attrs["source"] = "station"
    ds[cf_var].attrs["measurement_type"] = "in_situ"

    # Add instrument specs if available
    if merged_metadata.get("manufacturer"):
        ds[cf_var].attrs["instrument_manufacturer"] = merged_metadata["manufacturer"]

    if merged_metadata.get("model"):
        ds[cf_var].attrs["instrument_model"] = merged_metadata["model"]

    # Add key specs based on instrument type
    for spec_key in ["accuracy", "spectral_range", "temperature_range",
                     "measurement_range", "response_time", "calibration_uncertainty"]:
        if merged_metadata.get(spec_key):
            ds[cf_var].attrs[spec_key] = str(merged_metadata[spec_key])

    # Deployment details
    if merged_metadata.get("serial_number"):
        ds[cf_var].attrs["serial_number"] = merged_metadata["serial_number"]

    if merged_metadata.get("installation_height") is not None:
        ds[cf_var].attrs["sensor_height"] = f"{merged_metadata['installation_height']} m"
    elif merged_metadata.get("measurement_height") is not None:
        ds[cf_var].attrs["sensor_height"] = f"{merged_metadata['measurement_height']} m"

    # Auto-generate comment
    auto_comment = _generate_station_comment(merged_metadata)

    # Merge with user comment (append by default)
    user_comment = merged_metadata.get("comment", "")
    comment_replace = merged_metadata.get("comment_replace")

    if comment_replace:
        # Rare: full override
        ds[cf_var].attrs["comment"] = comment_replace
    elif user_comment:
        # Common: append
        ds[cf_var].attrs["comment"] = f"{auto_comment} {user_comment}"
    else:
        # Default: just auto
        ds[cf_var].attrs["comment"] = auto_comment

    # Quality assessment
    _add_quality_assessment(ds, cf_var)


def _generate_station_comment(metadata: dict[str, Any]) -> str:
    """Generate auto comment for station measurements."""
    instrument_desc = ""
    if metadata.get("manufacturer") and metadata.get("model"):
        instrument_desc = f" using {metadata['manufacturer']} {metadata['model']}"

    measurement_type = "Direct measurement from weather station"

    return f"{measurement_type}{instrument_desc}."


def _add_nldas2_provenance(
        ds: xr.Dataset,
        cf_var: str,
        param_config: dict[str, Any],
        merged_metadata: dict[str, Any]
) -> None:
    """
    Add provenance for NLDAS2 reanalysis variables.

    Documents:
    - Data type (reanalysis)
    - Model system
    - Spatial/temporal interpolation
    - References
    """
    ds[cf_var].attrs["source"] = "nldas2"
    ds[cf_var].attrs["data_type"] = "reanalysis"
    ds[cf_var].attrs["model"] = "NLDAS-2 (North American Land Data Assimilation System)"
    ds[cf_var].attrs["spatial_resolution"] = "0.125 degree (~12.5 km)"
    ds[cf_var].attrs["temporal_resolution"] = "1 hour"

    # Auto-generate comment
    auto_comment = (
        "Derived from NLDAS-2 reanalysis data. "
        "Spatially interpolated to site location. "
        "Hourly temporal resolution."
    )

    # Merge with user comment
    user_comment = merged_metadata.get("comment", "")
    comment_replace = merged_metadata.get("comment_replace")

    if comment_replace:
        ds[cf_var].attrs["comment"] = comment_replace
    elif user_comment:
        ds[cf_var].attrs["comment"] = f"{auto_comment} {user_comment}"
    else:
        ds[cf_var].attrs["comment"] = auto_comment

    # References
    default_ref = "doi:10.1175/JCLI-D-20-0982.1"
    if merged_metadata.get("references"):
        ds[cf_var].attrs["references"] = f"{default_ref}, {merged_metadata['references']}"
    else:
        ds[cf_var].attrs["references"] = default_ref

    # Quality assessment
    _add_quality_assessment(ds, cf_var)


def _add_pvlib_provenance(
        ds: xr.Dataset,
        cf_var: str,
        param_config: dict[str, Any],
        merged_metadata: dict[str, Any],
        dataframes: dict[str, pd.DataFrame] | None = None
) -> None:
    """
    Add provenance for pvlib-derived solar radiation variables.

    Introspects dataframes to document actual inputs and corrections.

    Documents:
    - Data type (derived)
    - Method (pvlib function)
    - Atmospheric corrections applied
    - Input data sources
    - References
    """
    ds[cf_var].attrs["source"] = "pvlib"
    ds[cf_var].attrs["data_type"] = "derived"

    # Determine pvlib method from source
    source = param_config.get("source", "").lower()
    if "dirindex" in source:
        method = "pvlib.irradiance.dirindex (Perez-Ineichen decomposition)"
        ref = "Perez et al. (1990) doi:10.1016/0038-092X(90)90055-H"
    elif "disc" in source:
        method = "pvlib.irradiance.disc (DISC decomposition model)"
        ref = "Maxwell (1987) SERI/TR-215-3087"
    else:
        method = f"pvlib ({source})"
        ref = "pvlib documentation: https://pvlib-python.readthedocs.io"

    ds[cf_var].attrs["method"] = method

    # Introspect dataframes to determine atmospheric corrections
    corrections_applied = []
    pressure_source = None
    dew_point_method = None

    if dataframes:
        # Check for pressure data
        for df_key in ["MET", "met", "station"]:
            df = dataframes.get(df_key)
            if df is not None:
                if "pressure" in df.columns or "BP_mbar" in df.columns:
                    corrections_applied.append("surface_pressure")
                    pressure_source = "station barometer"
                    break

        # Check for temperature and humidity (implies dew point)
        has_temp = False
        has_rh = False
        for df_key in ["MET", "met", "station"]:
            df = dataframes.get(df_key)
            if df is not None:
                if "temperature" in df.columns or "AirT_2M" in df.columns:
                    has_temp = True
                if "relative_humidity" in df.columns or "RH" in df.columns:
                    has_rh = True

        if has_temp and has_rh:
            corrections_applied.append("dew_point_temperature")
            dew_point_method = "computed from air temperature and relative humidity"

    if corrections_applied:
        ds[cf_var].attrs["atmospheric_corrections"] = " ".join(corrections_applied)

        if pressure_source:
            ds[cf_var].attrs["pressure_source"] = pressure_source

        if dew_point_method:
            ds[cf_var].attrs["dew_point_method"] = dew_point_method

    # Auto-generate comment
    corrections_desc = ""
    if corrections_applied:
        corr_list = ", ".join(corrections_applied)
        corrections_desc = f" Atmospheric corrections applied for {corr_list}."

    auto_comment = f"Derived using {method}.{corrections_desc}"

    # Merge with user comment
    user_comment = merged_metadata.get("comment", "")
    comment_replace = merged_metadata.get("comment_replace")

    if comment_replace:
        ds[cf_var].attrs["comment"] = comment_replace
    elif user_comment:
        ds[cf_var].attrs["comment"] = f"{auto_comment} {user_comment}"
    else:
        ds[cf_var].attrs["comment"] = auto_comment

    # References
    if merged_metadata.get("references"):
        ds[cf_var].attrs["references"] = f"{ref}, {merged_metadata['references']}"
    else:
        ds[cf_var].attrs["references"] = ref

    # Quality assessment
    _add_quality_assessment(ds, cf_var)


def _add_derived_provenance(
        ds: xr.Dataset,
        cf_var: str,
        param_config: dict[str, Any],
        merged_metadata: dict[str, Any]
) -> None:
    """
    Add provenance for derived variables (global_fraction, brunt, etc.).

    Documents:
    - Data type (derived)
    - Method description
    - References if applicable
    """
    ds[cf_var].attrs["source"] = param_config.get("source", "derived")
    ds[cf_var].attrs["data_type"] = "derived"

    # Auto-generate comment based on source
    source = param_config.get("source", "").lower()
    if "global_fraction" in source:
        auto_comment = "Derived from global shortwave radiation using fixed diffuse fraction."
    elif "global_coszenith" in source:
        auto_comment = "Derived from global shortwave radiation using cosine of solar zenith angle."
    elif "brunt" in source:
        auto_comment = "Derived using Brunt equation from temperature and vapor pressure."
    else:
        auto_comment = f"Derived from {source}."

    # Merge with user comment
    user_comment = merged_metadata.get("comment", "")
    comment_replace = merged_metadata.get("comment_replace")

    if comment_replace:
        ds[cf_var].attrs["comment"] = comment_replace
    elif user_comment:
        ds[cf_var].attrs["comment"] = f"{auto_comment} {user_comment}"
    else:
        ds[cf_var].attrs["comment"] = auto_comment

    # References if provided
    if merged_metadata.get("references"):
        ds[cf_var].attrs["references"] = merged_metadata["references"]

    # Quality assessment
    _add_quality_assessment(ds, cf_var)


def _add_quality_assessment(ds: xr.Dataset, cf_var: str) -> None:
    """
    Add quality assessment to variable.

    Phase 3 approach: Document quality in attributes.
    Phase 5 will add QC arrays only when quality varies.
    """
    values = ds[cf_var].values
    has_missing = np.any(np.isnan(values)) if np.issubdtype(values.dtype, np.floating) else False

    if not has_missing:
        # Homogeneous quality
        ds[cf_var].attrs["quality_assessment"] = "All values consistent quality"
    else:
        # Variable quality - note coverage in attribute
        valid_pct = 100 * np.count_nonzero(~np.isnan(values)) / len(values)
        ds[cf_var].attrs["quality_assessment"] = f"Data coverage: {valid_pct:.1f}%"


# =============================================================================
# ENHANCED build_netcdf_dataset (Phase 3)
# =============================================================================

def build_netcdf_dataset(
        met_df: pd.DataFrame,
        meta: Mapping[str, Any] | None = None,
        *,
        parameters: Mapping[str, Mapping[str, Any]] | None = None,
        dataframes: dict[str, pd.DataFrame] | None = None,
        instrument_library_path: str | None = None,
) -> xr.Dataset:
    """
    Build a CF-1.10 timeSeries Dataset with provenance metadata.

    - Auto-generates methodology from source type
    - Introspects dataframes to document actual processing
    - Merges instrument library specs with config metadata
    - Adds streamlined global attributes
    - Documents quality assessment

    Args:
        met_df: DataFrame with meteorological data
        meta: Metadata dict (latitude, longitude, elevation_m, title, institution, etc.)
        parameters: Parameter configurations from config
        dataframes: Optional dict of source dataframes for introspection
        instrument_library_path: Optional path to custom instrument library

    Returns:
        xarray Dataset with rich metadata
    """
    if not isinstance(met_df.index, pd.DatetimeIndex):
        raise TypeError("met_df must be indexed by a pandas.DatetimeIndex")

    parameters = parameters or {}
    meta = dict(meta or {})
    dataframes = dataframes or {}

    # Load instrument library if specified
    library = None
    if instrument_library_path:
        try:
            library = InstrumentLibrary(instrument_library_path)
            logger.info(f"Loaded instrument library: {library}")
        except Exception as e:
            logger.warning(f"Failed to load instrument library: {e}")
    else:
        # Try to load default library (optional)
        try:
            library = InstrumentLibrary()
            logger.debug(f"Loaded default instrument library: {library}")
        except Exception as e:
            logger.debug(f"No default instrument library available: {e}")

    # coords: time, nv ----------------------------------------------------------
    time = _normalize_time_index(met_df.index)
    ds = xr.Dataset(coords={
        "time": ("time", time.values),
        "nv": ("nv", np.array([0, 1], dtype=int)),
    })
    ds["time"].attrs.update({
        "standard_name": "time",
        "long_name": "time of measurement",
        "axis": "T",
        "bounds": "time_bnds",
    })

    # time bounds: [start, start+step)
    step = _infer_step(time)
    tb = np.stack([time.values, (time + step).values], axis=1)
    ds["time_bnds"] = xr.DataArray(tb, dims=("time", "nv"))
    ds["time_bnds"].attrs.update({
        "long_name": "start and end of time interval",
        "comment": "Left-closed, right-open bounds: [start, end).",
    })

    # globals: CF compliance
    ds.attrs.update({"Conventions": "CF-1.10", "featureType": "timeSeries"})

    # Add streamlined global attributes
    _add_streamlined_global_attrs(ds, meta, parameters)

    def _var(name: str, values: np.ndarray, attrs: Mapping[str, Any]) -> None:
        ds[name] = xr.DataArray(values, dims=("time",))
        ds[name].attrs.update(dict(attrs))

    # Accept internal parameter keys OR legacy column labels
    def _vals_col(param_key: str, *, dtype=float) -> np.ndarray | None:
        if param_key in met_df.columns:
            return met_df[param_key].to_numpy(dtype=dtype)
        legacy = default_col_names.get(param_key)
        if legacy and legacy in met_df.columns:
            return met_df[legacy].to_numpy(dtype=dtype)
        return None

    def _has_col(param_key: str) -> bool:
        return _vals_col(param_key) is not None

    # --- Core meteorology with CF-standard base attributes --------------------
    if _has_col("pressure"):
        _var("air_pressure", _vals_col("pressure") * 100.0,
             {"standard_name": "air_pressure", "long_name": "air pressure",
              "units": "Pa", "cell_methods": "time: mean"})

    if _has_col("temperature"):
        _var("air_temperature", _vals_col("temperature"),
             {"standard_name": "air_temperature", "long_name": "air temperature",
              "units": "degC", "cell_methods": "time: mean"})

    if _has_col("relative_humidity"):
        _var("relative_humidity", _vals_col("relative_humidity") / 100.0,
             {"standard_name": "relative_humidity",
              "long_name": "relative humidity (fraction)",
              "units": "1", "cell_methods": "time: mean"})

    if _has_col("wind_speed"):
        _var("wind_speed", _vals_col("wind_speed"),
             {"standard_name": "wind_speed", "long_name": "wind speed",
              "units": "m s-1", "cell_methods": "time: mean"})

    if _has_col("wind_direction"):
        _var("wind_from_direction", _vals_col("wind_direction"),
             {"standard_name": "wind_from_direction",
              "long_name": "wind from direction",
              "units": "degree", "cell_methods": "time: mean"})

    if _has_col("precipitation"):
        _var("precipitation_amount", _vals_col("precipitation"),
             {"standard_name": "precipitation_amount",
              "long_name": "precipitation amount",
              "units": "kg m-2", "cell_methods": "time: sum"})

    # --- Short-wave & long-wave ------------------------------------------------
    if _has_col("global_shortwave"):
        _var("surface_downwelling_shortwave_flux_in_air", _vals_col("global_shortwave"),
             {"standard_name": "surface_downwelling_shortwave_flux_in_air",
              "long_name": "global shortwave flux",
              "units": "W m-2", "cell_methods": "time: mean"})

    if _has_col("diffuse_shortwave"):
        _var("surface_diffuse_downwelling_shortwave_flux_in_air", _vals_col("diffuse_shortwave"),
             {"standard_name": "surface_diffuse_downwelling_shortwave_flux_in_air",
              "long_name": "diffuse shortwave flux",
              "units": "W m-2", "cell_methods": "time: mean"})

    if _has_col("downwelling_lwir"):
        _var("surface_downwelling_longwave_flux_in_air", _vals_col("downwelling_lwir"),
             {"standard_name": "surface_downwelling_longwave_flux_in_air",
              "long_name": "downwelling longwave flux",
              "units": "W m-2", "cell_methods": "time: mean"})

    # Direct normal irradiance handling (existing DNI logic)
    if _has_col("direct_shortwave"):
        direct_vals = _vals_col("direct_shortwave")
        zenith_vals = _vals_col("solar_zenith")

        if zenith_vals is not None:
            # Have zenith: BHI = DNI * cos(zenith)
            zen_rad = np.deg2rad(zenith_vals)
            bhi = direct_vals * np.cos(zen_rad)
            _var("surface_direct_along_beam_shortwave_flux_in_air", bhi,
                 {"standard_name": "surface_direct_along_beam_shortwave_flux_in_air",
                  "long_name": "beam horizontal irradiance (BHI)",
                  "units": "W m-2", "cell_methods": "time: mean",
                  "comment": "BHI computed as DNI * cos(solar_zenith_angle)"})

            _var("surface_direct_along_beam_normal_shortwave_flux_in_air", direct_vals,
                 {"standard_name": "surface_direct_along_beam_normal_shortwave_flux_in_air",
                  "long_name": "direct normal irradiance (DNI)",
                  "units": "W m-2", "cell_methods": "time: mean"})
        else:
            # No zenith: assume direct values are DNI
            _var("surface_direct_along_beam_shortwave_flux_in_air", direct_vals,
                 {"standard_name": "surface_direct_along_beam_shortwave_flux_in_air",
                  "long_name": "direct beam irradiance",
                  "units": "W m-2", "cell_methods": "time: mean",
                  "comment": "Direct beam values (DNI or BHI depending on source)"})

    # --- Add provenance to variables --------------------------------
    if parameters:
        for param_name, param_config in parameters.items():
            cf_var = _PARAM_TO_CF.get(param_name)
            if not cf_var or cf_var not in ds:
                continue

            # Get metadata from config
            config_metadata = param_config.get("metadata", {})

            # Merge with instrument library if available
            merged_metadata = merge_instrument_metadata(library, config_metadata) if library else config_metadata

            # Determine source and add appropriate provenance
            source = param_config.get("source", "").lower()

            if source in ("met", "station"):
                _add_station_provenance(ds, cf_var, param_config, merged_metadata)

            elif source == "nldas2":
                _add_nldas2_provenance(ds, cf_var, param_config, merged_metadata)

            elif source.startswith("pvlib"):
                _add_pvlib_provenance(ds, cf_var, param_config, merged_metadata, dataframes)

            elif source in ("global_fraction", "global_coszenith", "brunt"):
                _add_derived_provenance(ds, cf_var, param_config, merged_metadata)

            else:
                # Generic provenance for other sources
                if merged_metadata.get("comment"):
                    ds[cf_var].attrs["comment"] = merged_metadata["comment"]
                _add_quality_assessment(ds, cf_var)

    # --- Optional visibility & aerosol -----------------------------------------
    if _has_col("visibility"):
        vis = _vals_col("visibility")
        if vis is not None:
            vis = np.where(np.asarray(vis, float) < 0.0, np.nan, vis)
            _var("visibility_in_air", vis,
                 {"standard_name": "visibility_in_air", "long_name": "visibility",
                  "units": "m", "cell_methods": "time: mean"})

    if _has_col("aerosol"):
        aer = _vals_col("aerosol")
        if aer is not None:
            _var("aerosol_legacy", aer,
                 {"long_name": "legacy aerosol indicator from .met",
                  "units": str(default_met_units.get("aerosol", "")),
                  "comment": "Not CF AOD; preserved for provenance."})

    # ---- convenience time variables -------------------------------------------
    iso = pd.DatetimeIndex(time).strftime("%Y-%m-%dT%H:%M:%SZ").to_numpy(dtype=object)
    _var("iso_time", iso, {"long_name": "timestamp ISO8601 (UTC)"})

    _var("day_of_year", pd.Series(time).dt.dayofyear.to_numpy(),
         {"long_name": "day of year (1..366)", "units": "1"})

    # ---- Coverage statistics ---------------------------------------------------
    present_core = [v for v in _CORE_VARS if v in ds]
    if present_core:
        fracs = []
        for v in present_core:
            arr = ds[v].values
            valid = np.count_nonzero(~np.isnan(arr)) if np.issubdtype(arr.dtype, np.floating) else arr.size
            fracs.append(float(valid) / float(arr.size))
        min_frac = float(min(fracs)) if fracs else 1.0
        ds.attrs["coverage_min_fraction_core"] = min_frac
        ds.attrs["coverage_ok"] = int(min_frac >= _COVERAGE_THRESHOLD)

    return ds


# =============================================================================
# WRITE FUNCTIONS
# =============================================================================

def write_netcdf(ds: xr.Dataset, path: Path, *, engine: str | None = None) -> None:
    """Serialize Dataset to NetCDF."""
    engine = engine or "netcdf4"
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    # Ensure CF-style time encodings
    units = "seconds since 1970-01-01 00:00:00"
    cal = "standard"
    if "time" in ds:
        enc = dict(ds["time"].encoding or {})
        enc.setdefault("units", units)
        enc.setdefault("calendar", cal)
        ds["time"].encoding = enc
    if "time_bnds" in ds:
        encb = dict(ds["time_bnds"].encoding or {})
        encb.setdefault("units", units)
        encb.setdefault("calendar", cal)
        ds["time_bnds"].encoding = encb

    logger.info(f"Writing NetCDF to {path}")
    ds.to_netcdf(path, engine=engine)


def write_outputs(
        met_df: pd.DataFrame,
        *,
        outfile_met: Path | None,
        outfile_nc: Path | None,
        output_format: str = "met",
        netcdf_meta: Mapping[str, Any] | None = None,
        header: str | None = None,
        parameters: Parameters | None = None,
        netcdf_engine: str | None = None,
        dataframes: dict[str, pd.DataFrame] | None = None,
        instrument_library: str | None = None,
) -> None:
    """
    Unified writer: writes legacy .met, NetCDF, or both.
    """
    wrote = False

    if output_format in {"met", "both"} and outfile_met is not None:
        if header is None or parameters is None:
            raise ValueError("write_outputs: header and parameters required for '.met' output")
        write_met_data(met_df, str(outfile_met), header=header, parameters=parameters)
        wrote = True

    if output_format in {"netcdf", "both"} and outfile_nc is not None:
        ds = build_netcdf_dataset(
            met_df,
            meta=netcdf_meta or {},
            parameters=parameters or {},
            dataframes=dataframes,
            instrument_library_path=instrument_library,
        )
        write_netcdf(ds, outfile_nc, engine=netcdf_engine or "netcdf4")
        wrote = True

    if not wrote:
        logger.warning("write_outputs: nothing written (check output_format and file paths)")


def create_header(location_name: str, latitude: float, longitude: float,
                  elevation: float, start_range: str, end_range: str, freq: str) -> str:
    """Create header for legacy .met file."""
    if location_name is None:
        location_name = "Location"

    start_date = datetime.strptime(start_range, "%Y-%m-%d %H:%M")
    year = start_date.year

    header = f"{location_name} Met Data from {start_range} to {end_range} at {freq} resolution\n"
    header += "Elevation(m) Latitude Longitude GMT-UTC Year\n"
    header += f"{elevation} {latitude} {longitude} 0 {year}\n"
    return header


def write_met_data(met_df: pd.DataFrame, outfile: str, header: str,
                   parameters: Parameters, write_source: bool = False) -> None:
    """Write legacy .met format file."""
    logger.info(f"Writing met data to {outfile}")
    max_lengths = {}

    for col in met_df.columns:
        decimals = default_met_decimal.get(col, 0)
        max_length = max(len(f'{item:.{decimals}f}') if isinstance(item, float) else len(str(item))
                         for item in met_df[col]) + 1
        max_lengths[col] = max(max_length, default_met_width[col])

    units = [default_met_units.get(col) for col in met_df.columns]

    with open(outfile, 'w') as f:
        f.write(header)
        for col in met_df.columns:
            f.write(f'{default_col_names[col]:<{max_lengths[col]}}')
        f.write('\n')

        for col, unit in zip(met_df.columns, units):
            f.write(f'{unit:<{max_lengths[col]}}')
        f.write('\n')

        if write_source:
            for col in met_df.columns:
                if col == 'day':
                    f.write('# Sources - ')
                elif col == 'hour' or col == 'minute':
                    continue
                else:
                    source = parameters.get(col, {}).get('source', '-')
                    f.write(f"{source:<{max_lengths[col]}}")
            f.write('\n')

        for index, row in met_df.iterrows():
            for col, item in zip(met_df.columns, row):
                decimals = default_met_decimal.get(col, 0)
                try:
                    formatted_item = f'{item:.{decimals}f}'
                except ValueError:
                    formatted_item = f'{item}'
                f.write(f'{formatted_item:<{max_lengths[col]}}')
            f.write('\n')